api/urls.py
from django.urls import path, reverse_lazy, re_path
from django.views.decorators.csrf import csrf_exempt
from rest_framework_simplejwt import views as jwt_views
from .views import (LoginView, OauthDeclaraciones, estadisticasGraficasView, estadisticasView,
                    declaracionesJsonView, consultaEstatusTaskJSONDeclaracion, eliminarProcesoJSON, ActualizarUsuarioInfoPerFija)

urlpatterns = [
    path("iniciar_sesion/", csrf_exempt(OauthDeclaraciones.as_view())),
    path("v2/declaraciones/", csrf_exempt(OauthDeclaraciones.as_view())),
    path("token/", LoginView.as_view(), name='token_obtain_pair'),
    path("token/refresh/", jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path("estadisticas/", csrf_exempt(estadisticasView.as_view())),
    path("estadisticas-graficas/", estadisticasGraficasView, name='estadisticas-graficas'),
    path("actualizar_usuario_info/", csrf_exempt(ActualizarUsuarioInfoPerFija.as_view()), name='actualizar_usuario_info'),
    path("declaraciones-json/", declaracionesJsonView, name='declaraciones-json'),
    re_path(r'^estatus_declaraciones_json/$', consultaEstatusTaskJSONDeclaracion, name='estatus_declaraciones_json'),
    re_path(r'^eliminar_declaraciones_json/$', eliminarProcesoJSON, name='eliminar_declaraciones_json'),

]

declaraciones/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', include('sitio.urls')),
    path('admin/', admin.site.urls),
    path('declaracion/', include('declaracion.urls')),
    path('api/', include('api.urls')),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name ='reset_password'),  
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name ='password_reset_done'),  
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name ='password_reset_confirm'),  
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name ='password_reset_complete')
]


admin.site.site_header = 'Administración de Declaraciones'
admin.site.site_title = 'Administración de Declaraciones'
admin.site.index_title =  'Bienvenido a la administración del sistema'

declaracion/models/informacion_personal.py
import uuid
import os
from django.contrib.auth.models import User
from django.db import models
from django.db.models import CASCADE
from django.urls import reverse_lazy

from .catalogos import (CatPaises, CatEstadosCiviles,
                        CatTiposDeclaracion, CatRegimenesMatrimoniales,
                        CatGradosAcademicos, CatEstatusEstudios,
                        CatDocumentosObtenidos, CatEntesPublicos,
                        CatOrdenesGobierno,CatSectoresIndustria,
                        CatFuncionesPrincipales, CatAmbitosLaborales,
                        CatTiposRelacionesPersonales, CatPoderes,
                        CatTipoPersona, CatEntidadesFederativas, CatTipoVia,
                        CatMunicipios, CatMonedas,CatTiposOperaciones,CatEstatusDeclaracion,CatPuestos,CatAreas)
from django.db.models.signals import post_delete
from django.dispatch import receiver

#Se agrego variable global para los campos de modelos que lo necesiten ya que la informaciòn es la misma
TIPO_OPERACION = [
    ('AGREGAR', 'Agregar'),
    ('MODIFICAR', 'Modificar'),
    ('SIN_CAMBIO', 'Sin cambio'),
    ('BAJA', 'Baja')
]


class InfoPersonalFija(models.Model):
    """
    En este modelo se guarda la información personal del declarante
    """
    nombres = models.CharField(max_length=255, blank=True)
    apellido1 = models.CharField(max_length=255, blank=True, verbose_name="Apellido Paterno")
    apellido2 = models.CharField(max_length=255, blank=True, verbose_name="Apellido Materno")
    curp = models.CharField(max_length=255, blank=True)
    puesto = models.CharField(max_length=255, blank=True, null=True)
    cat_puestos = models.ForeignKey(CatPuestos, on_delete=models.DO_NOTHING, blank=True, null=True,verbose_name="Puesto") # AGREGADO 10/03/21 GG
    rfc = models.CharField(max_length=255, blank=True)
    telefono = models.CharField(max_length=14, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True, null=True)
    cat_ente_publico = models.ForeignKey(CatEntesPublicos, on_delete=models.DO_NOTHING, blank=True, null=True)
    cat_entidades_federativas = models.ForeignKey(CatEntidadesFederativas, on_delete=models.DO_NOTHING, null=True, blank=True)
    nombre_ente_publico = models.CharField(max_length=300, null=True, blank=True)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    cat_pais = models.ForeignKey(CatPaises, on_delete=models.DO_NOTHING, null=True, blank=True)
    otro_ente = models.CharField(max_length=255, blank=True, null=True)
    fecha_inicio = models.DateField(blank=True, null=True)
    sended = models.BooleanField(blank=True, null=True, default=False)

    def nombre_completo(self):
        return u"{} {} {}".format(self.nombres, self.apellido1,self.apellido2)



class Declaraciones(models.Model):
    """
    Modelo que guarda información de la declaración
    """
    folio = models.UUIDField(primary_key=False, default=uuid.uuid4, editable=False)
    fecha_recepcion = models.DateTimeField(blank=True, null=True)
    fecha_declaracion = models.DateField(null=True, auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    cat_tipos_declaracion = models.ForeignKey(CatTiposDeclaracion, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_estatus = models.ForeignKey(CatEstatusDeclaracion, on_delete=models.DO_NOTHING, default=1)
    avance = models.IntegerField(blank=True,default=0)
    info_personal_fija = models.ForeignKey(InfoPersonalFija, on_delete=models.DO_NOTHING)
    extemporanea = models.BooleanField(blank=True, null=True, default=0)
    datos_publicos = models.BooleanField(blank=True, null=True, default=0)


class Domicilios(models.Model):
    """
    Modelo que guarda información de los domicilios
    ---------
    Debido a que existen multiples personas relacionadas que se crearán en la declaración 
    muchas contarán con direcciones propias(ej. Dependientes economicos)
    """
    cp = models.CharField(max_length=255, blank=True)
    colonia = models.CharField(max_length=255, blank=True)
    nombre_via = models.CharField(max_length=255, blank=True)
    num_exterior = models.CharField(max_length=255, blank=True)
    num_interior = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    cat_entidades_federativas = models.ForeignKey(CatEntidadesFederativas, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_pais = models.ForeignKey(CatPaises, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_tipo_via = models.ForeignKey(CatTipoVia, on_delete=models.DO_NOTHING, null=True, blank=True)
    municipio = models.ForeignKey(CatMunicipios, on_delete=models.DO_NOTHING,blank=True, null=True)
    ciudadLocalidad = models.CharField(max_length=100, blank=True, null=True)
    estadoProvincia = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        ordering=('pk',)

    def __str__(self):
        try: 
            return self.nombre_via + self.num_exterior + self.num_interior + self.colonia + self.cp  
        except:
            return "Domicilio"


class Observaciones(models.Model):
    """
    Modelo que guarda las observaciones por secciones
    """
    observacion = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.observacion


class InfoPersonalVar(models.Model):
    """
    Modelo que guarda información de multiples personas relacionadas a una declaración del declarante
    ---------
    Uso principal: Guarda información de
                                        -Pareja
                                        -Dependientes economicos
                                        -Empresa
                                        -Cliente
                                        -Etc, Más en el catálogo tipoPersona
    """
    TIPO_DECLARANTE = 1
    TIPO_DEPENDIENTE = 2
    TIPO_EMPRESA = 3
    TIPO_SOCIO = 4
    TIPO_CLIENTE = 5
    TIPO_SOCIEDAD = 6
    TIPO_INSTITUCION = 7
    TIPO_FIDEICOMISARIO = 8
    TIPO_FIDEICOMITENTE = 9
    TIPO_FIDUCIARIO = 10
    TIPO_COPROPIETARIO = 12
    TIPO_PROPIETARIO_ANTERIOR = 13
    TIPO_PRESTATARIO = 14
    es_fisica = models.BooleanField(blank=True, null=True, default=None)
    razon_social = models.CharField(max_length=255, blank=True, null=True)
    nombres = models.CharField(max_length=255, blank=True)
    apellido1 = models.CharField(max_length=255, blank=True)
    apellido2 = models.CharField(max_length=255, blank=True)
    curp = models.CharField(max_length=255, blank=True)
    rfc = models.CharField(max_length=255, blank=True)
    homoclave = models.CharField(max_length=3, blank=True, null=True)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    num_id_identificacion = models.CharField(max_length=255, blank=True)
    email_personal = models.CharField(max_length=255, blank=True)
    tel_particular = models.CharField(max_length=255, blank=True)
    tel_movil = models.CharField(max_length=255, blank=True)
    cat_entidades_federativas = models.ForeignKey(CatEntidadesFederativas, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_estados_civiles = models.ForeignKey(CatEstadosCiviles, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_pais = models.ForeignKey(CatPaises, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_regimenes_matrimoniales = models.ForeignKey(CatRegimenesMatrimoniales, on_delete=models.DO_NOTHING, null=True, blank=True)
    declaraciones = models.ForeignKey(Declaraciones, on_delete=models.DO_NOTHING)
    domicilios = models.ForeignKey(Domicilios, on_delete=models.DO_NOTHING, blank=True, null=True)
    observaciones = models.ForeignKey(Observaciones, on_delete=models.DO_NOTHING, blank=True, null=True)
    cat_tipo_persona = models.ForeignKey(CatTipoPersona, on_delete=models.DO_NOTHING, blank=True, null=True)
    cat_sectores_industria = models.ForeignKey(CatSectoresIndustria, on_delete=models.DO_NOTHING, blank=True, null=True)
    otro_sector = models.CharField(max_length=255, blank=True, null=True)
    otro_estado_civil = models.CharField(max_length=255, blank=True, null=True)
    actividad_economica = models.CharField(max_length=255, blank=True, null=True)
    ocupacion_girocomercial = models.CharField(max_length=255, blank=True, null=True)
    nombre_negocio = models.CharField(max_length=255, blank=True, null=True)
    rfc_negocio = models.CharField(max_length=50, blank=True, null=True) #/AGREGADO
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    nacionalidades = models.ManyToManyField(CatPaises, through='Nacionalidades', related_name="info_personal_var_nacionalidaes", blank=True)
    activos_bienes = models.ManyToManyField(
        'ActivosBienes',
        through='BienesPersonas',
        through_fields=('info_personal_var', 'activos_bienes'),
        related_name="info_personal_var_activos_bienes")


    class Meta:
        ordering=('pk',)

    def __str__(self):
        return self.rfc

    def nombre_completo(self):
        if self.es_fisica:
            return ("%s %s %s")%(self.nombres ,self.apellido1,self.apellido2)
        else:
            return self.razon_social

    def domicilio(self):
        return [self.domicilios]

    def observacion(self):
        return [self.observaciones]

    def nacionalidad(self):
        try:
            return self.nacionalidades.all()
        except:
            return None

    def tipo(self):
        return self.cat_tipo_persona_id

    def sectores_industrias(self):
        try:
            if self.cat_sectores_industria.default:

declaracion/forms/confirmacion.py
from django import forms
from django.core.validators import FileExtensionValidator


class ConfirmacionForm(forms.Form):
   datos_publicos = forms.TypedChoiceField(
                    coerce=lambda x: x == 'True',
                    choices=((False, 'False'), (True, 'True')),
                    widget=forms.RadioSelect,
                    required=False
                   )

declaracion/forms/ingresosEsp.py
from bootstrap_datepicker_plus import DatePickerInput
from django import forms
from django.forms import  TextInput,Textarea
from declaracion.models import IngresosDeclaracion
import datetime

YEARS= [x for x in range(1920,datetime.date.today().year+1)]

class IngresosDeclaracionForm(forms.ModelForm):
    fecha_ingreso= forms.DateField(label='Fecha de nacimiento', widget=forms.SelectDateWidget(years=YEARS), required=False)
    fecha_conclusion= forms.DateField(label='Fecha de nacimiento', widget=forms.SelectDateWidget(years=YEARS),required=False)
    
    def __init__(self, *args, **kwargs):
        super(IngresosDeclaracionForm, self).__init__(*args, **kwargs)
        self.fields['ingreso_mensual_otros_ingresos'].widget.attrs['readonly'] = True
        self.fields['ingreso_mensual_neto'].widget.attrs['readonly'] = True
        #self.fields['ingreso_mensual_pareja_dependientes'].widget.attrs['readonly'] = True
        self.fields['ingreso_mensual_total'].widget.attrs['readonly'] = True

    def clean(self):
        fecha_ingreso = self.cleaned_data.get('fecha_ingreso')
        fecha_salida = self.cleaned_data.get('fecha_conclusion')

        if fecha_ingreso and fecha_salida:
            if fecha_ingreso > fecha_salida:
                raise forms.ValidationError("FECHA INGRESO: Fecha de ingreso no puede ser superior a la fecha de conclusión")

    class Meta:
        model = IngresosDeclaracion
        fields = '__all__'
        exclude = ['declaraciones', 'observaciones']
        widgets = {
            'tipo_servicio': Textarea(attrs={'rows': 4})
        }

declaracion/views/api.py
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.views import View

from declaracion.models import Declaraciones
from datetime import datetime
from django.core.paginator import Paginator
from django.shortcuts import render

class RegistrosView(View):
    template_name = "reportes/publico.json.html"


    def get(self, request, *args, **kwargs):
        api_key = request.GET.get('api_key')
        sort = request.GET.get('sort')
        page = request.GET.get('page')
        page_size = request.GET.get('page_size')
        nombres = request.GET.get('nombres')
        apellido1 = request.GET.get('apellido1')
        apellido2 = request.GET.get('apellido2')
        rfc = request.GET.get('rfc')
        curp = request.GET.get('rfc')

        id = request.GET.get('id')
        actualizacion = request.GET.get('actualizacion')
        rfc_solicitante = request.GET.get('rfc_solicitante')
        filter = False


        declaraciones = Declaraciones.objects
        if id and id != "":
            declaraciones = declaraciones.filter(folio=id)
            filter=True
        if rfc and rfc != "":
            declaraciones = declaraciones.filter(info_personal_fija__rfc=rfc.upper())
            filter=True
        if curp and curp != "":
            declaraciones = declaraciones.filter(info_personal_fija__curp=curp.upper())
            filter = True
        if nombres and nombres != "":
            declaraciones = declaraciones.filter(info_personal_fija__nombres__contains=nombres.upper())
            filter = True
        if apellido1 and apellido1 != "":
            declaraciones = declaraciones.filter(info_personal_fija__apellido1__contains=apellido1.upper())
            filter = True
        if apellido2 and apellido2 != "":
            declaraciones = declaraciones.filter(info_personal_fija__apellido2__contains=apellido2.upper())
            filter = True
        if sort and sort.upper() == "ASC":
            declaraciones = declaraciones.order_by('fecha_declaracion')
            filter = True
        elif sort and sort.upper() == "DESC":
            declaraciones = declaraciones.order_by('-fecha_declaracion')
            filter = True
        if actualizacion and actualizacion != "":
            actualizacion = datetime.strptime(actualizacion, "%Y-%m-%d")
            declaraciones = declaraciones.filter(fecha_declaracion__gte=actualizacion)
            filter = True
        if not filter:
            declaraciones=declaraciones.all()

        if page_size and page:
            paginator = Paginator(declaraciones, int(page_size))
            declaraciones = paginator.get_page(int(page))
        response = render_to_string(self.template_name, {
            'declaraciones': declaraciones
        })
        return HttpResponse(content = response,content_type="application/json")

templates/declaracion/declaracion-fiscal.html
{% extends "layout/base.html" %}
{% load static %}
{% block header_title %}Declaración fiscal{% endblock %}
{% load bootstrap4 %}
{% load flujo_declaracion %}
{% block content %}
<div class="container-fluid h-100">
    <div class="row h-100">
        {% include 'layout/sidebar.html' %}
        <div class="col-md-9">
        	<nav aria-label="breadcrumb">
                <ol class="breadcrumb text-sm text-uppercase font-weight-extralight">
                    <li class="breadcrumb-item"><a href="#" class="text-reset">Declaración en curso</a></li>
                    <li class="breadcrumb-item"><a href="#" class="text-reset">Información personal</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Información general</li>
                </ol>
            </nav>
            <h1 class="text-uppercase text-black h5">Declaracion fiscal</span></h1>
            <h2 class="h6 mb-3 text-uppercase">1. Subir archivo <span class="text-black mx-1">|</span> <span class="text-primary font-weight-light">I. Subir archivo PDF correspondiente</span></h2>
            {% include 'layout/informacion-registrada.html' with registros=informacion_registrada titulo_uno="Archivo guardado" fiscal="fiscal"%}
            <form action="{% url 'declaracion:declaracion-fiscal' folio_declaracion %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ declaracion }}
                <div class="row">
                  {% include 'layout/no_aplica.html' %}
                  {{ prueba }}
                </div>
                <div class="row row-form" style="{% if checked %}display: none;{% endif %}">
                    {% if subir_archivo %}
                   
                    <div class="col-md-12">
                        <div class="file-upload">
                          <div class="image-upload-wrap" id="image-upload-wrap-pdf">
                            <input class="file-upload-input" type='file' name="declaracion_fiscal-archivo_pdf" id="id_declaracion_fiscal-archivo_pdf" onchange="readURL(this);" accept=".pdf" tipo="pdf"/>
                            <div class="drag-text">
                              <h3>Arrastre y suelte el archivo <b>PDF</b> aquí</h3>
                            </div>
                          </div>
                          <div class="file-upload-content" id="file-upload-content-pdf">
                            <img class="file-upload-image" src="{% static 'src/img/pdf_bn.png'%}" alt="Archivo PDF"/>
                            <div class="image-title-wrap">
                              <button type="button" onclick="removeUpload('pdf')" class="btn btn-outline-primary text-uppercase font-weight-bold">Eliminar<br>  <span class="image-title" id="image-title-pdf">Archivo</span></button>
                            </div>
                          </div>
                        </div>
                    </div>

                    <!--<div class="col-md-6">
                        <div class="file-upload">
                          <div class="image-upload-wrap" id="image-upload-wrap-xml">
                            <input class="file-upload-input" type='file' name="declaracion_fiscal-archivo_xml" id="id_declaracion_fiscal-archivo_xml" onchange="readURL(this);" accept=".xml" tipo="xml"/>
                            <div class="drag-text">
                              <h3>Arrastre y suelte el archivo <b>XML</b> aquí</h3>
                            </div>
                          </div>
                          <div class="file-upload-content" id="file-upload-content-xml">
                            <img class="file-upload-image" src="{% static 'src/img/xml_bn.png'%}" alt="Archivo XML"/>
                            <div class="image-title-wrap">
                              <button type="button" onclick="removeUpload('xml')" class="btn btn-outline-primary text-uppercase font-weight-bold">Eliminar<br>  <span class="image-title" id="image-title-xml">Archivo</span></button>
                            </div>
                          </div>
                        </div>
                    </div>-->
                    {% endif %}

                </div>
                 {% include 'layout/guardar.html' %}
                  <div class="row"><div class="col-12"><br/></div></div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/declaracion/municipios.html
<option value="">---------</option>
{% for municipio in municipios %}
<option value="{{ municipio.pk }}">{{ municipio.valor }}</option>
{% endfor %}

templates/declaracion/registro.html
{% extends "layout/base.html" %}
{% load static %}
{% block header_title %}Regístrate{% endblock %}
{% load bootstrap4 %}
{% block content %}

<section class="container container-offset-x my-md-7 py-7">
  
  <figure class="text-center">
    <img src="{% static 'src/img/SEAJAL-Declaraciones-Crear_cuenta-Grafico.png' %}" alt="crea tu cuenta">
    <figcaption class="txtCAzulF"> <h1>Crea tu cuenta </h1> </figcaption>
  </figure>

  <p class="font-weight-light">Todos lo campos son obligatorios</p>
  <form id="form_registro" class="block_submit" action="{% if is_staff %}{% url 'declaracion:nuevo-usuario' %}{% else %}{% url 'declaracion:nuevo' %}{% endif %}" method="post" novalidate>
    {% csrf_token %}
    <div class="row">
      <div class="col-lg-10">
        <div class="row">
          <div class="col-md-6">
            {% bootstrap_field form.fecha placeholder="16/01/2018" addon_before='<span class="" >Fecha Ingreso</span>' %}
          </div>
          <div class="col-md-12"></div>
          <div class="col-md-6">
            {% bootstrap_field form.nombres placeholder="Nombre(s)" field_class="solo_letras" addon_before='<span class="" >Nombre(s)</span>' %}
          </div>
          <div class="col-md-6">
              {% bootstrap_field form.apellido1 placeholder="Primer apellido" field_class="solo_letras" addon_before='<span class="" >Primer apellido</span>' %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.apellido2 placeholder="Segundo apellido" field_class="solo_letras" addon_before='<span class="" >Segundo apellido</span>' %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.rfc placeholder="RFC con homoclave" field_class='valida_rfc' addon_before='<span class="" >RFC</span>' %}
          </div>
          <div class="col-md-12">
            {% bootstrap_field form.ente_publico placeholder="Ente publico" field_class="solo_letras"  addon_before='<span class="" >Ente Público</span>' %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.areas placeholder="Area" field_class="solo_letras"  addon_before='<span class="" >Área</span>' %}
          </div>
          <div class="col-md-6">
            <div class="input-group mb-3">             
              <div class="input-group-prepend"><label class="input-group-text">Empleo</label></div>           
                <!--Selectpiker para la busqueda puestos add J -  21/07/2023-->  
              <select id="id_puesto" name="puesto" class="form-control selectpicker" data-live-search="true">              
              </select>
            </div>
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.telefono placeholder="Teléfono" field_class="valida_telefono" addon_before='<span class="" >Teléfono</span>' %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.email placeholder="Correo electrónico" field_class='valida_email' addon_before='<span class="" >Correo Electrónico</span>'  %}
          </div>        
          <div class="col-md-6">
            {% bootstrap_field form.contrasena1 placeholder="Contraseña" addon_before='<span class="" >Contraseña</span>' %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.contrasena2 placeholder="Confirmar Contraseña" addon_before='<span class="" >Confirmar Contraseña</span>' %}
          </div>
          <div class="col-12 text-right">
            <div id="ms_terminos_condiciones"></div>
            <input type="checkbox" id="checkbox_crear_cuenta" onclick="onclick_check_terminos_condiciones()">
            <a 
              {% if file_terminos_condiciones %} 
                href="{{file_terminos_condiciones.url}}" 
                target="_blank" 
              {% else %}
                href="javascript:no_archivo_terminos_condiciones()"
              {% endif %}
                style="color: #015F78;font-size: large;font-weight: 400;width: 50px;height: 20px;"> 
              Acepto términos y condiciones
            </a>
          </div>
           {% if cap_bool %}
            <div class="col-12 text-right">
              <script src='https://www.google.com/recaptcha/api.js'></script>
               <div class="g-recaptcha" data-sitekey="{{ cap_webkey }}"></div>
             </div>
             <p style="color: #dc3545;    font-size: 80%; margin-left: 16px;">{{ error }}</p>
           {% endif %}
           
          <div class="col-12 text-right">
            <button type="submit" class="btn btn-success text-uppercase mt-5 block_boton" id="btn_crear_cuenta" disabled>Crear cuenta</button>
          </div>
        </div>
      </div>
    </div>
  </form>
</section>
{% endblock %}

templates/declaracion/usuario-no-registrado.html
{% extends "layout/base.html" %}
{% load static %}
{% block header_title %}No registrado{% endblock %}
{% load bootstrap4 %}
{% block content %}
<section class="container-fluid container-offset-x my-md-7 py-7">
  <figure class="text-center">
    <img src="{% static 'src/img/SEAJAL-Declaraciones-Crear_cuenta-Grafico.png' %}" alt="crea tu cuenta">
    <figcaption class="txtCAzulF">
    	<h1>RFC no registrado previamente por usuario administrativo</h1>
    	<h2 class="txtCVerdeSeco">Para crear su cuenta solicite darse de alta</h2>
  	    <p class="text-md font-weight-semibold text-gray-dark mb-0"><a href="{% url 'declaracion:nuevo' %}" class="btn btn-primary bgCVerdeSeco borderless">Regresar</a></p>
    </figcaption>
  </figure>
</section>
{% endblock %}